### ISSUE TITLE
boost::numeric bindings

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/hybridization#5]
Some old boost::numeric bindings are used in the code (`boost/numeric/bindings`). They are not available in boost anymore and were only a part of alps. What shall we do with them?

**Comment by egull** [comment]
I have removed them, at the cost of calling lapack / blas directly.

**Comment by matthiastroyer** [comment]
We will then need to call lapack/blas directly also from other ALPS codes.

**Comment by matthiastroyer** [comment]
They were never part of Boost and still are not. That’s why we distribute them with ALPS. The boost numeric bindings have just recently moved to a new git repository in case you want to update to the latest version.
